flog/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('flog.views',
    (r'^(?P<yyyy>\d{4})/(?P<mm>\d{1,2})/(?P<dd>\d{1,2})/$', 'day'),
    (r'^$', 'index'),
)

flog/forms.py
from django import forms
from django.conf import settings
from django.contrib import admin
from django.contrib.admin import widgets             
from django.db import models
from django.forms.util import ErrorList

from tagging.forms import TagField

from flog.models import Swallow, ENTRY_HELP_TEXT


class EntryForm(forms.Form):
    """Flog entry form
    """
    txt = forms.CharField(help_text=ENTRY_HELP_TEXT)

flog/templates/flog/base.html
{% extends "base.html" %}
{% load media %}



{% block breadcrumbs %}{{ block.super }}{% endblock %}



{% block content %}

<div id="body">
{% block body %}{% endblock %}
<div class="clearer" style="clear: both;">&nbsp;</div>
</div><!-- /body -->

{% endblock %}



{% block sidebar %}

<div class="block">
  {% if request.user.is_authenticated %}
  <h3>{{ request.user.username }}</h3>
  <p>
  <a href="/accounts/logout/?next_page=/">Log out</a>
  </p>
  {% else %}
  <h3>You're not logged in</h3>
  <ul>
  <li><a href="/accounts/login/?next=/">Log in</a></li>
  <li><a href="/accounts/register/">Register</a></li>
  </ul>
  {% endif %}
  <div class="clearer"></div>
</div>

{% endblock %}

flog/templates/flog/day-mobile.html
{% load media %}
{% block content %}
<h1>
<form name="entry" method="post" action="/flog/">
<a href="/">home</a>
&raquo; <a href="/flog/">flog</a> &nbsp;
entry&nbsp;<input name="txt" id="id_txt" type="text"/>
<input type="submit" value="flog"/>
</form>
</h1>

<pre>
lb     {% if day.weight_lbs %}{{ day.weight_lbs }}{% endif %}
cal    {% if day.calories %}{{ day.calories }}{% endif %}
coffee {% if day.coffee_cups %}{{ day.coffee_cups }}{% endif %}
sleep  {% if day.hours_slept %}{{ day.hours_slept }}{% endif %}
</pre>

<pre>{% for s in swallows %}
[<a href="/admin/flog/swallow/{{ s.id }}/">edit</a>] {{ s.created }} {{ s.title }} {{ s.serving_size }} {{ s.tags }} {{ s.calories }}{% endfor %}
</pre>

<pre>{% for e in entries %}
[<a href="/admin/flog/entry/{{ e.id }}/">edit</a>] {{ e.created }} {{ e.txt }}{% endfor %}
</pre>

<pre>
p1 {{ day.p1 }}
</pre>

{% endblock content %}

flog/templates/flog/day.html
{% extends "flog/base.html" %}
{% load media %}

{% block js %}
<script type="text/javascript" src="{% media "js/jquery.js" %}"></script>
<script type="text/javascript" src="{% media "js/jquery.sparkline.min.js" %}"></script>
<script type="text/javascript">
  $(function() {
    $('.weight').sparkline();
    $('.calories').sparkline();
    $('.sleep').sparkline();
    $('.coffee_cups').sparkline();
    $('.p1').sparkline();
  });
</script>
{% endblock js %}

{% block breadcrumbs %}{{ block.super }}
&raquo; <a href="../../../">flog</a>
&raquo; {{ today|date:"j M Y" }}
{% if yesterday %}<a href="../../../{{ yesterday|date:"Y/m/d" }}/">&lt;</a>{% else %}&lt;{% endif %}
{% if tomorrow %}<a href="../../../{{ tomorrow|date:"Y/m/d" }}/">&gt;</a>{% else %}&gt;{% endif %}
{% endblock %}

{% block content %}





<form name="entry" method="post" action="/flog/">
<input name="txt" id="id_txt" type="text" size="60"/>
<input type="submit" value="flog"/>
</form>

<table cellspacing="0" cellpadding="0" border="0">
  <tr>
    <td> lb </td>
    <td> &nbsp; </td>
    <td align="right"> {% if day.weight_lbs %}{{ day.weight_lbs }}{% endif %} </td>
    <td> &nbsp; </td>
    <td> <span class="weight">{{ day.sparkline_weight|join:"," }}</span> </td>
  </tr>
  <tr>
    <td> cal </td>
    <td> &nbsp; </td>
    <td align="right"> {% if day.calories %}{{ day.calories }}{% endif %} </td>
    <td> &nbsp; </td>
    <td> <span class="calories">{{ day.sparkline_calories|join:"," }}</span> </td>
  </tr>
  <tr>
    <td> coffee </td>
    <td> &nbsp; </td>
    <td align="right"> {% if day.coffee_cups %}{{ day.coffee_cups }}{% endif %} </td>
    <td> &nbsp; </td>
    <td> <span class="coffee_cups">{{ day.sparkline_coffee_cups|join:"," }}</span> </td>
  </tr>
  <tr>
    <td> sleep </td>
    <td> &nbsp; </td>
    <td align="right"> {% if day.hours_slept %}{{ day.hours_slept }}{% endif %} </td>
    <td> &nbsp; </td>
    <td> <span class="sleep">{{ day.sparkline_sleep|join:"," }}</span> </td>
  </tr>
</table>

<pre>{% for s in swallows %}
[<a href="/admin/flog/swallow/{{ s.id }}/">edit</a>] {{ s.created }} {{ s.title }} {{ s.serving_size }} {{ s.tags }} {{ s.calories }}{% endfor %}
</pre>

<pre>{% for e in entries %}
[<a href="/admin/flog/entry/{{ e.id }}/">edit</a>] {{ e.created }} {{ e.txt }}{% endfor %}
</pre>

<p>
p1 {{ day.p1 }} <span class="p1">{{ day.sparkline_p1|join:"," }}</span><br/>
</p>

{% endblock content %}

flog/templates/flog/index-mobile.html
{% load media %}
{% block content %}
<h1>
<form name="entry" method="post" action="">
<a href="/">home</a>
&raquo; <a href="">flog</a> &nbsp;
entry&nbsp;<input name="txt" id="id_txt" type="text"/>
<input type="submit" value="flog"/>
</form>
</h1>
{% endblock content %}

flog/templates/flog/index.html
{% extends "base.html" %}
{% load media %}

{% block breadcrumbs %}{{ block.super }}
&raquo; flog
{% endblock %}

{% block content %}

<form name="entry" method="post" action="">{% csrf_token %}
<input name="txt" id="id_txt" type="text" size="60"/>
<input type="submit" value="flog"/>
<br/>
{{ form.txt.help_text|safe }}
</form>

<pre>{% for s in swallows %}
[<a href="/admin/flog/swallow/{{ s.id }}/">edit</a>][<a href="{{ s.created|date:"Y/m/d" }}/">day</a>] {{ s.created }} {{ s.title }} {{ s.serving_size }} {{ s.tags }} {{ s.calories }}{% endfor %}
</pre>

<pre>{% for e in entries %}
[<a href="/admin/flog/entry/{{ e.id }}/">edit</a>][<a href="{{ e.created|date:"Y/m/d" }}/">day</a>] {{ e.created }} {{ e.txt }}{% endfor %}
</pre>

{% endblock content %}

flog/templates/flog/ok.html
<h1>
OK &laquo;
<a href="..{% if mobile %}/?mobile=1{% endif %}">back</a>
</h1>